# Generated by Django 3.2 on 2024-10-25 19:50

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre_title',
            new_name='GenreTitle',
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.models.validate_year], verbose_name='Год выпуска'),
        ),
    ]
